Allow observable's subscription as loading value
moff/angular2-ladda pull request #21
Opened 2017-08-04 05:01 UTC by rumitparakhiya

This commit allows observable's subscription as loading value. Assigning a subscription will start the spinner and will stop it once the subscription is complete

2021-03-29 10:27 UTC, andreialecu commented
@theodorejb this would be pretty useful. Any reason why it wasn't merged?

2021-03-29 10:29 UTC, andreialecu commented on README.md
> +        this.isLoading = this.http.get('https://jsonplaceholder.typicode.com/posts')
```suggestion
        this.subscription = this.http.get('https://jsonplaceholder.typicode.com/posts')
```

2021-03-30 07:44 UTC, rparakhiya commented
@andreialecu The suggestion was applied and the MR is updated to resolve conflicts.

2021-03-31 14:06 UTC, theodorejb requested changes
Besides the inline comments I added, the ESLint checks currently aren't passing (run `npm run lint` to check). Also I'm not sure the approach in this PR will even work - one of the buttons in the src/app test project would need to be changed to use a subscription to test whether it functions as expected.

2021-03-31 14:06 UTC, theodorejb commented on projects/ladda/src/lib/ladda.directive.ts
> +import {Subscription} from 'rxjs/Subscription';
This needs to be imported from `'rxjs'` directly rather than `'rxjs/Subscription'`.

2021-03-31 14:06 UTC, theodorejb commented on projects/ladda/src/lib/ladda.directive.ts
> +        let loading: boolean = typeof this.loading === 'number' || this.loading instanceof Subscription || !!this.loading;
Won't this cause `loading` to be `true` even after the observable completes (`loading` will still be an instance of `Subscription`)?

2021-03-31 14:06 UTC, theodorejb commented on projects/ladda/src/lib/ladda.directive.ts
> +        let wasLoading: boolean = (this.loading instanceof Subscription) ? false : typeof previousValue === 'number' || !!previousValue;
I believe this should check `previousValue` rather than `this.loading`.

2021-03-31 14:06 UTC, theodorejb commented on README.md
> +import {Subscription} from 'rxjs/Subscription';
`Subscription` should be imported directly from `'rxjs'`.

2021-05-05 04:01 UTC, rparakhiya commented
Closing this as implementation won't work as expected.

2021-05-05 04:01 UTC, closed without merging